# ~/Documentos/terra/k8s-master/mi-nginx-chart/values.yaml
replicaCount: 2

image:
  repository: nginx
  tag: "1.25.4"

service:
  port: 80

resources:
  requests:
    cpu: "10m"
    memory: "32Mi"
  limits:
    cpu: "50m"
    memory: "64Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

probes:
  liveness:
    path: "/"
    port: 80
  readiness:
    path: "/"
    port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "srelab.local"

persistence:
  enabled: true
  size: "1Gi"
  mountPath: "/var/www/uploads"

rbac:
  enabled: true
  developerUser: "dev-junior"

# Nueva configuración: Tarea programada (Scraper Bursátil)
scraperCron:
  enabled: true
  schedule: "*/5 * * * *"
  image: "python:3.9-alpine"
