# ~/Documentos/terra/k8s-master/mi-nginx-chart/values.yaml
replicaCount: 2

image:
  repository: nginx
  tag: "1.25.4"

service:
  port: 80

resources:
  requests:
    cpu: "10m"
    memory: "32Mi"
  limits:
    cpu: "50m"
    memory: "64Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

probes:
  liveness:
    path: "/"
    port: 80
  readiness:
    path: "/"
    port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "srelab.local"

persistence:
  enabled: true
  size: "1Gi"
  mountPath: "/var/www/uploads"

rbac:
  enabled: true
  developerUser: "dev-junior"

scraperCron:
  enabled: true
  schedule: "*/5 * * * *"
  image: "python:3.9-alpine"

database:
  enabled: true
  name: "mascotapp_db"
  user: "admin_backend"
  password: "SuperSecretPassword2026!"

initContainer:
  enabled: true
  image: "busybox:1.28"
  command: 
    - sh
    - -c
    - 'echo "Iniciando chequeo de pre-requisitos SRE..."; sleep 15; echo "Base de datos lista. Permitiendo arranque de Nginx."'

sidecar:
  enabled: true
  image: "busybox:1.28"

nodeConfig:
  enabled: true
  requireSSD: true

tolerations:
  - key: "uso"
    operator: "Equal"
    value: "sre-admin"
    effect: "NoSchedule"

networkPolicy:
  enabled: true

statefulDatabase:
  enabled: true
  replicas: 2

monitoringAgent:
  enabled: true
  image: "busybox:1.28"

pdb:
  enabled: true
  minAvailable: 1

namespaceQuota:
  enabled: true
  maxCPU: "1"
  maxMemory: "1Gi"
  maxPods: "15"

appConfig:
  mensaje: "SRE Lab: Formación Ofensiva 3-4-3"

securityOptions:
  enabled: true

# Nueva Configuración: Reglas de separación espacial
affinityOptions:
  enabled: true
