# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-cm
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Panel SRE</title>
      <style>
        body { font-family: Arial; text-align: center; margin-top: 50px; background-color: #f4f4f9; }
        h1 { color: #333; }
      </style>
    </head>
    <body>
      <h1>{{ .Values.appConfig.mensaje }}</h1>
      <p>Infraestructura GitOps Operativa</p>
    </body>
    </html>
