# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/cronjob.yaml
{{- if .Values.scraperCron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-bolsa-scraper
  labels:
    app: scraper
spec:
  schedule: "{{ .Values.scraperCron.schedule }}"
  
  # LA REGLA SRE DE LIMPIEZA VISUAL
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: scraper
        spec:
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: scraper
            image: "{{ .Values.scraperCron.image }}"
            command:
            - /bin/sh
            - -c
            - "echo 'Extrayendo datos de la Bolsa de Santiago...'; sleep 5; echo 'Datos bursátiles actualizados con éxito.'"
            
            # SOLUCIÓN: El contrato de Fair Play para pasar la cuota del Namespace
            resources:
              requests:
                cpu: "10m"
                memory: "32Mi"
              limits:
                cpu: "20m"
                memory: "64Mi"
                
          restartPolicy: OnFailure
{{- end }}
