# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/cronjob.yaml
{{- if .Values.scraperCron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-bolsa-scraper
spec:
  schedule: "{{ .Values.scraperCron.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          # --- INICIO DEL PASE VIP ---
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          # --- FIN DEL PASE VIP ---
          
          containers:
          - name: scraper
            image: {{ .Values.scraperCron.image }}
            command:
            - /bin/sh
            - -c
            - "echo 'Iniciando conexion a la Bolsa de Santiago...'; sleep 2; echo 'Calculando market share...'; sleep 2; echo 'Extraccion exitosa. Datos listos para la presentacion gerencial.'"
          restartPolicy: OnFailure
{{- end }}
