# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: webserver
spec:
  # Solo define replicas estáticas si el HPA está APAGADO.
  # Si el HPA está encendido, ArgoCD soltará el control de las réplicas.
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        
        # El sensor que reinicia el contenedor si se congela
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.path }}
            port: {{ .Values.probes.liveness.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        
        # El sensor que avisa cuando el contenedor ya puede recibir tráfico
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.path }}
            port: {{ .Values.probes.readiness.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        
        # Montamos el ConfigMap en la ruta del HTML de Nginx
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      
      # Definimos el volumen que extrae los datos del ConfigMap
      volumes:
      - name: html-volume
        configMap:
          name: {{ .Release.Name }}-nginx-cm
