# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: webserver
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.path }}
            port: {{ .Values.probes.liveness.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.path }}
            port: {{ .Values.probes.readiness.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        
        volumeMounts:
        # 1. El volumen de la página web (ConfigMap)
        - name: html-volume
          mountPath: /usr/share/nginx/html
        # 2. El NUEVO volumen de datos persistentes
        {{- if .Values.persistence.enabled }}
        - name: data-volume
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
      
      volumes:
      # 1. Definición del volumen del ConfigMap
      - name: html-volume
        configMap:
          name: {{ .Release.Name }}-nginx-cm
      # 2. Definición del NUEVO volumen persistente (PVC)
      {{- if .Values.persistence.enabled }}
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-nginx-pvc
      {{- end }}
