# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/networkpolicy.yaml
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-db-firewall
spec:
  # 1. ¿A QUIÉN PROTEGE ESTE MURO? A la Base de Datos
  podSelector:
    matchLabels:
      app: database
  
  # 2. ¿QUÉ TIPO DE TRÁFICO VAMOS A FILTRAR? El tráfico de entrada (Ingress)
  policyTypes:
  - Ingress
  
  # 3. LAS REGLAS DE LA PUERTA VIP:
  ingress:
  - from:
    # Solo permitimos la entrada si vienes de un Pod con esta etiqueta exacta
    - podSelector:
        matchLabels:
          app: webserver
    # Y solo te dejamos tocar este puerto específico
    ports:
    - protocol: TCP
      port: 3306
{{- end }}
