# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/pdb.yaml
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-nginx-pdb
spec:
  # REGLA DE ORO: Siempre debe haber al menos esta cantidad de Pods vivos
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: webserver
{{- end }}
