# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/rbac.yaml
{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-readonly-role
# Aquí definimos las reglas del juego
rules:
- apiGroups: [""] # El grupo principal de K8s
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"] # Solo mirar, no tocar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-readonly-binding
# A quién le damos el rol
subjects:
- kind: User
  name: {{ .Values.rbac.developerUser }}
  apiGroup: rbac.authorization.k8s.io
# Qué rol le estamos dando
roleRef:
  kind: Role
  name: {{ .Release.Name }}-readonly-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
