# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/rbac.yaml
{{- if .Values.rbac.enabled }}
# 1. Creamos la credencial del usuario
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Values.rbac.developerUser }}
---
# 2. Definimos las reglas del juego (Solo mirar, no tocar)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-viewer-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments", "services", "statefulsets"]
  verbs: ["get", "watch", "list"]
---
# 3. Asignamos el rol a la credencial
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-viewer-binding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ .Values.rbac.developerUser }}
  # Si no especificamos namespace en Helm, asumimos 'default'
  namespace: default
roleRef:
  kind: Role
  name: {{ .Release.Name }}-viewer-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
