# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-nginx-sa
  labels:
    app: webserver
# AutomountServiceAccountToken en false es el verdadero Zero Trust. 
# Le decimos a K8s: "Nginx no necesita hablar con la API, no le inyectes el token de acceso".
automountServiceAccountToken: false
