# ~/Documentos/terra/k8s-master/mi-nginx-chart/templates/statefulset.yaml
{{- if .Values.statefulDatabase.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: database
spec:
  serviceName: {{ .Release.Name }}-db-headless
  replicas: {{ .Values.statefulDatabase.replicas }}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      {{- if .Values.nodeConfig.enabled }}
      nodeSelector:
        hardware: ssd
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      containers:
      - name: mariadb
        image: "mariadb:10.11"
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-credentials
              key: DB_PASSWORD
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-credentials
              key: DB_NAME
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
          
        # SOLUCIÓN: Contrato de recursos para MariaDB
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
            
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
{{- end }}
